databases:
  - name: medicaldb
    plan: free

services:
  - type: web
    name: medical-record-service
    env: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: medicaldb
          property: connectionString
